### PR TITLE
chore: updated Remix dev command

### LINKED ISSUE #787: Update the Remix dev command
**Which problem is this feature request solving?**

The Remix dev command has changed. It's now `remix dev`

**Describe the solution you'd like**

Update the Remix dev command to `remix dev`

**Describe alternatives you've considered**

N/A

**Can you submit a pull request?**

Yes

### PR DESCRIPTION
**Pull request by nickytonline**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Updates the Remix dev command to `remix dev`. When the command was initially added, `remix dev` did not exist.

Closes #787 

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/framework-info/issues/new/choose) before writing your code 🧑‍💻. This
      ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a
      typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Comment by nickytonline** [comment]
@KyleBlankRollins, is there anywhere in the documentation that we mention `remix watch`? It's in our template, but I'm going to update it there.

**Comment by nickytonline** [comment]
I checked our docs and there is no mention of remix watch @KyleBlankRollins, so nothing to update there. There is only discussion of build commands for frameworks, including Remix, [https://github.com/netlify/docs/blob/main/docs/integrations/frameworks/index.md#remix](https://github.com/netlify/docs/blob/main/docs/integrations/frameworks/index.md?rgh-link-date=2022-07-14T18%3A34%3A44Z#remix)

**Review by orinokai — APPROVED** [review]
Saw the discussion on Slack, but looks like it's all resolved so 🚢

**Comment by ascorbic** [comment]
Wait, I thought the decision was to _not_ change this?

**Pull request merged**
