### PR TITLE
Update the build command and directory for Angular.js

### PR DESCRIPTION
**Pull request by charliegerard**
This PR updates the build command and directory for Angular.js sites, as per [this Slack thread](https://netlify.slack.com/archives/C012GT6MYKU/p1614183782058100?thread_ts=1614118421.044100&cid=C012GT6MYKU)

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
Thanks @charliegerard!

When you merge the PR can you prefix the commit message with `fix:` to create a patch version?

`chore:` are meant to be used for non user facing changes. 
See [here](https://github.com/googleapis/release-please#how-should-i-write-my-commits) for more info

**Comment by charliegerard** [comment]
😭  sorry @erezrokah I messed up and changed `chore` to `fix` in the commit description not the commit message 🤦‍♀️. How can i fix this?

**Comment by erezrokah** [comment]
I think it still worked https://github.com/netlify/framework-info/pull/151

**Comment by charliegerard** [comment]
Oh awesome, thanks!! 😃

**Pull request merged**
