### PR TITLE
feat: update next plugin package to install

### PR DESCRIPTION
**Pull request by ericapisani**
Currently blocked on other changes needing to be done first, have this open so it's ready to go when we need it

#### Summary
See [this issue](https://github.com/netlify/pod-ecosystem-frameworks/issues/174)

**A picture of a cute animal (not mandatory, but encouraged)**
PXL_20220804_202302722

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
🚀

**Review by ascorbic — CHANGES_REQUESTED** [review]
DO NOT MERGE

**Comment by ascorbic** [comment]
OK, can we change this so that it only applies for a feature flag? There should be examples somewhere.

**Comment by ericapisani** [comment]
@ascorbic I've added a check for a `build_use_next_runtime` feature flag, but just wanted to confirm that the systems for setting up a build would select the runtime first if the feature flag is enabled, or if there's additional filtering that needs to be done such as what we do for the minimum node version condition

**Comment by ascorbic** [comment]
Not using this now

**Pull request closed without merging**
